etcd:
  image: "weaveworks/kubernetes-anywhere:etcd"

kube-apiserver:
  image: "weaveworks/kubernetes-anywhere:apiserver"

kube-scheduler:
  image: "weaveworks/kubernetes-anywhere:scheduler"

kube-controller-manager:
  image: "weaveworks/kubernetes-anywhere:controller-manager"

#kubelet:
#  privileged: true
#  net: host
#  pid: host
#  volumes: 
#    - "/var/run/weave/weave.sock:/weave.sock"
#  image: "weaveworks/kubernetes-anywhere:kubelet"
#
#kube-proxy:
#  privileged: true
#  net: host
#  pid: host
#  image: "weaveworks/kubernetes-anywhere:proxy"
