etcd:
  image: "weaveworks/kubernetes-anywhere:etcd"
  hostname: "etcd1.weave.local"
  restart: "always"

apiserver:
  image: "weaveworks/kubernetes-anywhere:apiserver"
  hostname: "kube-apiserver.weave.local"
  restart: "always"
  links: [ "etcd" ]

scheduler:
  image: "weaveworks/kubernetes-anywhere:scheduler"
  hostname: "kube-scheduler.weave.local"
  restart: "always"
  links: [ "apiserver" ]

controller-manager:
  image: "weaveworks/kubernetes-anywhere:controller-manager"
  hostname: "kube-controller-manager.weave.local"
  restart: "always"
  links: [ "apiserver" ]

kubelet:
  privileged: true
  net: host
  pid: host
  volumes_from: [ "kubelet-volumes" ]
  image: "weaveworks/kubernetes-anywhere:kubelet"
  restart: "always"

proxy:
  privileged: true
  net: host
  pid: host
  image: "weaveworks/kubernetes-anywhere:proxy"
  restart: "always"

weavescope:
  image: weaveworks/scope:0.13.1
  privileged: true
  net: host
  pid: host
  ports:
  - "0.0.0.0:4040:4040"
  volumes:
  - "/var/run/:/var/run:rw"
  command:
  - "--probe.docker"
  - "true"
  - "--probe.kubernetes"
  - "true"
  - "--probe.kubernetes.api"
  - "http://kube-apiserver.weave.local:8080"
  restart: "always"
