etcd:
  image: "gcr.io/google_containers/etcd:2.0.13"
  hostname: "etcd.weave.local"
  command: "etcd --listen-peer-urls http://etcd:2380,http://etcd:7001 --listen-client-urls http://etcd:2379,http://etcd:4001 --advertise-client-urls http://etcd:2379,http://etcd:4001"

apiserver:
  image: "weaveworks/kubernetes-anywhere:apiserver"
  hostname: "kube-apiserver.weave.local"

scheduler:
  image: "weaveworks/kubernetes-anywhere:scheduler"
  hostname: "kube-scheduler.weave.local"

controller-manager:
  image: "weaveworks/kubernetes-anywhere:controller-manager"
  hostname: "kube-controller-manager.weave.local"

kubelet:
  privileged: true
  net: host
  pid: host
  volumes: [ "/var/run/weave/weave.sock:/weave.sock" ]
  image: "weaveworks/kubernetes-anywhere:kubelet"

proxy:
  privileged: true
  net: host
  pid: host
  image: "weaveworks/kubernetes-anywhere:proxy"
