etcd:
  image: "weaveworks/kubernetes-anywhere:etcd"
  hostname: "etcd.weave.local"

apiserver:
  image: "weaveworks/kubernetes-anywhere:apiserver"
  hostname: "kube-apiserver.weave.local"

scheduler:
  image: "weaveworks/kubernetes-anywhere:scheduler"
  hostname: "kube-scheduler.weave.local"

controller-manager:
  image: "weaveworks/kubernetes-anywhere:controller-manager"
  hostname: "kube-controller-manager.weave.local"

kubelet:
  privileged: true
  net: host
  pid: host
  volumes:
  - "/var/run/weave/weave.sock:/weave.sock"
  - "/:/rootfs:ro"
  - "/sys:/sys:ro"
  - "/dev:/dev"
  - "/var/lib/docker/:/var/lib/docker:rw"
  - "/var/lib/kubelet/:/var/lib/kubelet:rw"
  - "/var/run:/var/run:rw"
  - "/mnt/sda1/var/lib/docker/:/mnt/sda1/var/lib/docker:rw"
  image: "weaveworks/kubernetes-anywhere:kubelet"

proxy:
  privileged: true
  net: host
  pid: host
  image: "weaveworks/kubernetes-anywhere:proxy"

weavescope:
  image: weaveworks/scope:0.9.0
  privileged: true
  net: host
  pid: host
  ports:
  - "0.0.0.0:4040:4040"
  volumes:
  - "/var/run/:/var/run:rw"
  command:
  - "--probe.docker"
  - "true"
  - "--probe.kubernetes"
  - "true"
